import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as THREE from 'three';
import JSZip from 'jszip';
import {ArrowRight,BookOpen,Boxes,Check,CheckCircle2,ChevronRight,Code2,Download,ExternalLink,FileCode2,GitBranch,Layers3,LogIn,Menu,Play,Route,Search,Settings,ShieldCheck,Sparkles,Terminal,Upload,Users,Video,X} from 'lucide-react';
import './styles.css';

type Page='home'|'paths'|'path'|'lesson'|'roadmaps'|'roadmap'|'projects'|'project'|'resources'|'search'|'login'|'signup'|'dashboard'|'studio';
const paths=[
 {id:'html',title:'HTML',desc:'Build a semantic foundation for every web experience.',lessons:10,level:'Beginner',time:'4h 20m'},
 {id:'css',title:'CSS',desc:'Turn structure into responsive, polished interfaces.',lessons:12,level:'Beginner',time:'6h 10m'},
 {id:'javascript',title:'JavaScript',desc:'Add logic, interaction, APIs and browser behavior.',lessons:14,level:'Intermediate',time:'8h 40m'},
 {id:'react',title:'React',desc:'Build component-driven interfaces that scale.',lessons:16,level:'Intermediate',time:'9h 30m'},
 {id:'node',title:'Node.js',desc:'Create backend services, APIs and server-side tools.',lessons:15,level:'Intermediate',time:'8h 50m'},
 {id:'fullstack',title:'Full Stack',desc:'Connect frontend, backend, databases and deployment.',lessons:28,level:'Advanced',time:'18h 30m'}
];
const lessons=[
 ['01','How the web is structured','HTML','Understand documents, elements and semantic structure.'],
 ['02','Elements & attributes','HTML','Build useful content with semantic elements and attributes.'],
 ['03','Links, images & media','HTML','Connect pages and add accessible media.'],
 ['04','Lists, tables & forms','HTML','Collect and present structured information.'],
 ['05','Semantic page layout','HTML','Use header, nav, main, section, article and footer correctly.'],
 ['06','Forms & validation','HTML','Create usable forms with browser validation.'],
 ['07','Accessibility foundations','HTML','Build keyboard-friendly and meaningful markup.'],
 ['08','Metadata & SEO','HTML','Give search engines and social previews useful context.'],
 ['09','Project: profile page','HTML','Combine your skills into a responsive profile.'],
 ['10','Project review & next steps','HTML','Review the foundation and move into CSS.']
];
const projects=[
 {id:'dashboard',title:'Responsive Admin Dashboard',tech:'HTML · CSS · JavaScript',level:'Intermediate',desc:'A responsive dashboard with navigation, metrics, tables and interactive filters.'},
 {id:'todo',title:'Focus To-Do App',tech:'HTML · CSS · JavaScript',level:'Beginner',desc:'A focused task manager with filters, local persistence and completion states.'},
 {id:'weather',title:'Weather Explorer',tech:'JavaScript · APIs',level:'Intermediate',desc:'A clean weather interface designed around API data, loading and error states.'}
];
const resources=[
 ['VS Code Setup','Install VS Code, extensions, terminal basics and project folders.','Setup'],
 ['Git & GitHub','Learn repositories, commits, branches, remotes, push, pull and README workflow.','Git'],
 ['Deploy Your Website','Take a project live with GitHub, Vercel and a custom domain.','Deployment'],
 ['Build Your Own Website','Plan, design, code, test and ship a complete website.','Project'],
 ['AI for Coding','Use AI to explain, debug, review and learn without skipping verification.','AI']
];
const roadmapNodes=[
 ['01','Computer Basics','Foundations','Start here'],
 ['02','HTML','Frontend','Structure'],
 ['03','CSS','Frontend','Responsive UI'],
 ['04','JavaScript','Frontend','Logic'],
 ['05','Git / GitHub','Workflow','Version control'],
 ['06','React','Frontend','Components'],
 ['07','Node.js','Backend','Server'],
 ['08','Express','Backend','APIs'],
 ['09','Database','Backend','Data'],
 ['10','APIs','Full Stack','Integration'],
 ['11','Authentication','Full Stack','Secure access'],
 ['12','Deployment','DevOps','Go live'],
 ['13','Real Projects','Portfolio','Build & ship']
];

function go(page:Page,id?:string){const u=id?'/'+page+'/'+id:'/'+page;if(page==='home')history.pushState({},'', '/');else history.pushState({},'',u);window.dispatchEvent(new PopStateEvent('popstate'))}
function route():{page:Page,id?:string}{const p=location.pathname.split('/').filter(Boolean);if(!p.length)return{page:'home'};const map:any={paths:'paths',path:'path',lesson:'lesson',roadmaps:'roadmaps',roadmap:'roadmap',projects:'projects',project:'project',resources:'resources',search:'search',login:'login',signup:'signup',dashboard:'dashboard',studio:'studio'};return{page:map[p[0]]||'home',id:p[1]}}
function useRoute(){const[,setTick]=useState(0);useEffect(()=>{const f=()=>setTick(x=>x+1);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);return route()}

function Scene3D(){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!ref.current)return;const el=ref.current;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,0,7.2);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);
 const root=new THREE.Group();scene.add(root);
 const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.22,2),new THREE.MeshStandardMaterial({color:0x18b957,emissive:0x063b20,metalness:.75,roughness:.18}));root.add(core);
 const wire=new THREE.Mesh(new THREE.IcosahedronGeometry(1.58,2),new THREE.MeshBasicMaterial({color:0x63f39a,wireframe:true,transparent:true,opacity:.3}));root.add(wire);
 const ring1=new THREE.Mesh(new THREE.TorusGeometry(2.05,.012,12,180),new THREE.MeshBasicMaterial({color:0x38bdf8,transparent:true,opacity:.65}));ring1.rotation.x=.75;root.add(ring1);
 const ring2=ring1.clone();ring2.rotation.x=1.25;ring2.rotation.y=.5;root.add(ring2);
 const pts=new THREE.BufferGeometry(),count=900,pos=new Float32Array(count*3);for(let i=0;i<count;i++){const r=3+Math.random()*3.5,a=Math.random()*Math.PI*2;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=(Math.random()-.5)*5.5;pos[i*3+2]=(Math.random()-.5)*5.5}pts.setAttribute('position',new THREE.BufferAttribute(pos,3));scene.add(new THREE.Points(pts,new THREE.PointsMaterial({color:0x4ade80,size:.018,transparent:true,opacity:.7})));
scene.add(new THREE.AmbientLight(0xb8ffda,.55));const light=new THREE.PointLight(0x22c55e,8,14);light.position.set(2,2,4);scene.add(light);const cyan=new THREE.PointLight(0x38bdf8,3,12);cyan.position.set(-3,-1,2);scene.add(cyan);
const mouse={x:0,y:0};const move=(e:MouseEvent)=>{mouse.x=e.clientX/innerWidth-.5;mouse.y=e.clientY/innerHeight-.5};addEventListener('mousemove',move);
let raf=0;const animate=()=>{raf=requestAnimationFrame(animate);root.rotation.y+=.0025;root.rotation.x+=(mouse.y*.22-root.rotation.x)*.025;root.position.x+=(mouse.x*.35-root.position.x)*.025;wire.rotation.y-=.004;ring1.rotation.z+=.006;ring2.rotation.z-=.004;renderer.render(scene,camera)};animate();
const resize=()=>{const w=el.clientWidth,h=el.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)};addEventListener('resize',resize);resize();
return()=>{cancelAnimationFrame(raf);removeEventListener('mousemove',move);removeEventListener('resize',resize);renderer.dispose();el.removeChild(renderer.domElement)}} ,[]);
return <div className="scene3d" ref={ref}/>;
}

function Nav(){const[open,setOpen]=useState(false);return <header className="nav"><div className="nav-inner"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">&lt;/&gt;</span><span>Coding<span>Vibes</span></span></button><nav className={open?'nav-links open':'nav-links'}>{[['paths','Paths'],['roadmaps','Roadmaps'],['projects','Projects'],['resources','Resources']].map(([p,t])=><button key={p} onClick={()=>{go(p as Page);setOpen(false)}}>{t}</button>)}</nav><div className="nav-actions"><button className="icon-btn" aria-label="Search" onClick={()=>go('search')}><Search size={18}/></button><button className="login-link" onClick={()=>go('login')}>Log in</button><button className="primary small" onClick={()=>go('signup')}>Start learning</button><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div></header>}

function Footer(){return <footer><div className="footer-main"><div><button className="brand" onClick={()=>go('home')}><span className="brand-mark">&lt;/&gt;</span><span>Coding<span>Vibes</span></span></button><p>Learn visually. Build confidently.</p></div><div className="footer-links"><button onClick={()=>go('paths')}>Learning Paths</button><button onClick={()=>go('roadmaps')}>Roadmaps</button><button onClick={()=>go('projects')}>Projects</button><button onClick={()=>go('resources')}>Resources</button></div></div><div className="footer-bottom">© 2026 Coding Vibes <span>Built for curious builders.</span></div></footer>}

function Home(){return <><Nav/><main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> A learning platform for builders</div><h1>Learn code.<br/><em>Build what matters.</em></h1><p>Structured paths, real projects and an interactive roadmap designed to take you from your first line of code to full-stack confidence.</p><div className="hero-actions"><button className="primary" onClick={()=>go('paths')}>Start a learning path <ArrowRight/></button><button className="secondary" onClick={()=>go('roadmaps')}>Explore the roadmap <Route/></button></div><div className="trust"><span><CheckCircle2/> Hands-on lessons</span><span><CheckCircle2/> Real projects</span><span><CheckCircle2/> Learn at your pace</span></div></div><Scene3D/><div className="hero-label label-one">&lt;HTML /&gt;</div><div className="hero-label label-two">{'{ CSS }'}</div><div className="hero-label label-three">JS →</div></section>
<section className="section journey"><div className="section-head"><div><span className="kicker">YOUR CODING JOURNEY</span><h2>A clear path forward.</h2></div><button className="text-link" onClick={()=>go('roadmaps')}>View full roadmap <ArrowRight size={16}/></button></div><div className="roadmap-line">{[['01','Foundations','HTML · CSS'],['02','Interactivity','JavaScript'],['03','Components','React'],['04','Backend','Node · APIs'],['05','Ship it','Deploy · Git']].map((x,i)=><button className="road-node" key={x[0]} onClick={()=>go('roadmap','full-stack')}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small>{i<4&&<i/>}</button>)}</div></section>
<section className="section why"><div className="why-visual"><div className="glass-stack"><Code2/><span>01</span><b>Learn</b><p>Short, focused lessons.</p></div><div className="glass-stack offset"><Boxes/><span>02</span><b>Build</b><p>Practice with real projects.</p></div><div className="glass-stack offset2"><Route/><span>03</span><b>Ship</b><p>Follow a roadmap to production.</p></div></div><div><span className="kicker">WHY CODINGVIBES?</span><h2>Less guessing.<br/><em>More building.</em></h2><p className="lead">Everything is connected: learn a concept, practice it, use it in a project, then move forward with confidence.</p><div className="mini-list"><div><strong>01</strong><span><b>Structured</b> — know what to learn next.</span></div><div><strong>02</strong><span><b>Practical</b> — code instead of just watching.</span></div><div><strong>03</strong><span><b>Progressive</b> — beginner to full stack.</span></div></div></div></section>
<section className="cta"><div><span className="kicker">READY TO START?</span><h2>Your next build<br/><em>starts here.</em></h2><p>Pick a path and turn your next hour into real progress.</p><button className="primary" onClick={()=>go('paths')}>Explore learning paths <ArrowRight/></button></div></section></main><Footer/></>}

function PathList(){return <><Nav/><main className="listing"><PageHero kicker="LEARNING PATHS" title="Learn with direction." sub="Structured journeys from first concepts to production-ready skills."/><div className="filter-row"><button className="filter active">All</button><button className="filter">Beginner</button><button className="filter">Frontend</button><button className="filter">Backend</button><button className="filter">Full Stack</button></div><div className="card-grid">{paths.map(p=><button className="feature-card" key={p.id} onClick={()=>go('path',p.id)}><div className="card-icon"><BookOpen/></div><div><span className="card-meta">{p.level} · {p.time}</span><h3>{p.title}</h3><p>{p.desc}</p><div className="card-foot">{p.lessons} lessons <ChevronRight size={16}/></div></div></button>)}</div></main><Footer/></>}

function PageHero({kicker,title,sub}:{kicker:string,title:string,sub:string}){return <div className="page-hero"><span className="kicker">{kicker}</span><h1>{title}</h1><p>{sub}</p></div>}

function PathDetail({id}:{id?:string}){const p=paths.find(x=>x.id===id)||paths[0];const[completed,setCompleted]=useState(Number(localStorage.getItem('cv-progress-'+p.id)||0));return <><Nav/><main className="listing"><button className="back" onClick={()=>go('paths')}>← Learning Paths</button><div className="path-head"><div><span className="kicker">{p.level} · {p.time}</span><h1>{p.title} path</h1><p>{p.desc}</p></div><div className="progress-card"><span>YOUR PROGRESS</span><strong>{completed} / {p.lessons}</strong><div className="progress"><i style={{width:(completed/p.lessons*100)+'%'}}/></div></div></div><div className="lesson-list">{(p.id==='html'?lessons:Array.from({length:p.lessons},(_,i)=>[String(i+1).padStart(2,'0'),p.title+' lesson '+(i+1),'Lesson','Practical concepts and hands-on exercises.'])).map((l:any,i)=><button className="lesson-row" key={l[0]} onClick={()=>go('lesson',p.id+'-'+(i+1))}><span className="lesson-number">{l[0]}</span><div><span>{l[2]}</span><h3>{l[1]}</h3><p>{l[3]}</p></div><span className={i<completed?'lesson-check done':'lesson-check'}>{i<completed?<Check/>:<Play size={15}/>}</span><ChevronRight/></button>)}</div></main><Footer/></>}

function Lesson({id}:{id?:string}){const parts=(id||'html-1').split('-');const p=paths.find(x=>x.id===parts[0])||paths[0];const idx=Math.max(1,Number(parts[1]||1));const lesson=p.id==='html'?lessons[idx-1]:[String(idx).padStart(2,'0'),p.title+' lesson '+idx,p.title,'Practical concepts and hands-on exercises.'];const key='cv-complete-'+p.id+'-'+idx;const[done,setDone]=useState(localStorage.getItem(key)==='1');const code='<main>\\n  <h1>Build something today</h1>\\n  <p>Learn by shipping small projects.</p>\\n</main>';const complete=()=>{const n=!done;setDone(n);localStorage.setItem(key,n?'1':'0');if(n){const current=Number(localStorage.getItem('cv-progress-'+p.id)||0);localStorage.setItem('cv-progress-'+p.id,String(Math.max(current,idx)))}};return <><Nav/><main className="lesson-page"><button className="back" onClick={()=>go('path',p.id)}>← {p.title} path</button><div className="lesson-layout"><article><span className="kicker">{p.title.toUpperCase()} · LESSON {lesson[0]}</span><h1>{lesson[1]}</h1><p className="lead">{lesson[3]}</p><div className="video"><video controls preload="metadata" poster="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1400&q=80" src="https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"/><div className="video-badge"><Video size={14}/> Lesson video</div></div><div className="lesson-content"><h2>What you'll learn</h2><p>Learn the concept through a short explanation, then immediately apply it in a small task. The lesson structure is designed for practice rather than passive watching.</p><div className="code"><div>index.html <span>HTML</span><button onClick={()=>navigator.clipboard?.writeText(code)}>Copy</button></div><pre>{code}</pre></div><h2>Practice</h2><p>Create a small page that uses the concept from this lesson. Keep it simple, test it in your browser and compare your result with the next lesson.</p><div className="practice"><Terminal/><div><b>Practice task</b><span>Build a small component using today's concept and make it responsive.</span></div></div></div></article><aside className="lesson-side"><div className="side-card"><span>YOUR PROGRESS</span><strong>{done?'Complete':'In progress'}</strong><div className="progress"><i style={{width:done?'100%':'15%'}}/></div></div><button className={done?'complete done':'complete'} onClick={complete}>{done?<CheckCircle2/>:<CheckCircle2/>}{done?'Completed':'Mark as complete'}</button><div className="side-card"><span>NEXT LESSON</span><b>{idx<p.lessons?(p.id==='html'?lessons[idx]?.[1]:p.title+' lesson '+(idx+1)):'Path complete'}</b>{idx<p.lessons&&<button onClick={()=>go('lesson',p.id+'-'+(idx+1))}>Continue <ArrowRight size={15}/></button>}</div></aside></div></main><Footer/></>}

function Roadmaps(){return <><Nav/><main className="listing"><PageHero kicker="ROADMAPS" title="See the whole journey." sub="Visual maps that show prerequisites, sequence and the next skill to build."/><div className="card-grid">{[['full-stack','Full Stack Roadmap','13 connected milestones','Beginner → Advanced'],['frontend','Frontend Roadmap','9 milestones','HTML → React'],['backend','Backend Roadmap','10 milestones','Node → APIs → Data']].map(x=><button className="feature-card" key={x[0]} onClick={()=>go('roadmap',x[0])}><div className="card-icon"><Route/></div><div><span className="card-meta">{x[3]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div><ChevronRight/></button>)}</div></main><Footer/></>}

function Roadmap(){const[done,setDone]=useState<string[]>(JSON.parse(localStorage.getItem('cv-roadmap')||'[]'));const toggle=(n:string)=>{const next=done.includes(n)?done.filter(x=>x!==n):[...done,n];setDone(next);localStorage.setItem('cv-roadmap',JSON.stringify(next))};return <><Nav/><main className="roadmap-page"><button className="back" onClick={()=>go('roadmaps')}>← Roadmaps</button><div className="roadmap-title"><span className="kicker">FULL STACK · INTERACTIVE</span><h1>From first line to production.</h1><p>Click a milestone to mark it complete. The sequence is intentional: each stage prepares you for the next.</p></div><div className="roadmap-canvas">{roadmapNodes.map((n,i)=><button className={done.includes(n[0])?'map-node done':'map-node'} key={n[0]} onClick={()=>toggle(n[0])}><span>{n[0]}</span><div><small>{n[2]}</small><b>{n[1]}</b><em>{n[3]}</em></div>{i<roadmapNodes.length-1&&<i/>}</button>)}</div></main><Footer/></>}

function Projects(){const[q,setQ]=useState('');const filtered=projects.filter(p=>(p.title+p.tech+p.desc).toLowerCase().includes(q.toLowerCase()));return <><Nav/><main className="listing"><PageHero kicker="PROJECTS" title="Learn by building." sub="Realistic projects with source structure, previews, code and documentation."/><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects or technologies..."/></div><div className="card-grid project-grid">{filtered.map(p=><button className="project-card" key={p.id} onClick={()=>go('project',p.id)}><div className="project-preview"><span>&lt;/&gt;</span><div>{p.title}</div></div><span className="card-meta">{p.level}</span><h3>{p.title}</h3><p>{p.desc}</p><small>{p.tech}</small></button>)}</div></main><Footer/></>}

function projectFiles(p:any){if(p.id==='todo')return {'index.html':'<main id="app"></main>','style.css':'body{font-family:system-ui;background:#071019;color:white}','app.js':'const tasks=[];'};if(p.id==='weather')return {'index.html':'<main id="weather"></main>','style.css':'body{font-family:system-ui;background:#06111c;color:white}','app.js':'fetch(\"https://api.example.com/weather\").then(r=>r.json())'};return {'index.html':'<main class="dashboard"><h1>Dashboard</h1><section class="stats"></section></main>','style.css':'body{font-family:system-ui;background:#071019;color:white}.dashboard{padding:40px}','app.js':'document.querySelector(\".dashboard\")'}}

function Project({id}:{id?:string}){const p=projects.find(x=>x.id===id)||projects[0];const files=projectFiles(p);const[active,setActive]=useState(Object.keys(files)[0]);const preview='<html><body style="font-family:system-ui;background:#071019;color:#bfffd1;padding:40px"><h1>'+p.title+'</h1><p>'+p.desc+'</p><div style="border:1px solid #1e4935;padding:20px;border-radius:14px">Live project preview</div></body></html>';const download=async()=>{const zip=new JSZip();Object.entries(files).forEach(([n,c])=>zip.file(n,c as string));const blob=await zip.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=p.id+'.zip';a.click();URL.revokeObjectURL(a.href)};return <><Nav/><main className="project-detail"><button className="back" onClick={()=>go('projects')}>← Projects</button><div className="project-head"><div><span className="kicker">{p.level} · {p.tech}</span><h1>{p.title}</h1><p>{p.desc}</p></div><div className="project-actions"><button className="primary" onClick={download}><Download/> Download ZIP</button><button className="secondary" onClick={()=>navigator.clipboard?.writeText(files[active])}>Copy code</button></div></div><div className="project-workspace"><aside className="file-tree"><b>FILES</b>{Object.keys(files).map(f=><button className={f===active?'selected':''} onClick={()=>setActive(f)} key={f}><FileCode2 size={15}/>{f}</button>)}</aside><section className="source-view"><div className="source-head">{active}<span>Source</span></div><pre>{files[active]}</pre></section><section className="live-preview"><div className="source-head">Live Preview <ExternalLink size={15}/></div><iframe title="project preview" sandbox="allow-scripts" srcDoc={preview}/></section></div></main><Footer/></>}

function Resources(){return <><Nav/><main className="listing"><PageHero kicker="RESOURCES & TUTORIALS" title="The setup behind the code." sub="Practical guides for the tools and workflows developers use every day."/><div className="resource-grid">{resources.map((r,i)=><button className="resource-card" key={i}><div><span className="card-meta">{r[2]}</span><h3>{r[0]}</h3><p>{r[1]}</p></div><ChevronRight/></button>)}</div></main><Footer/></>}

function SearchPage(){const[q,setQ]=useState('');const results=useMemo(()=>[...paths.map(p=>({title:p.title,type:'Learning Path',desc:p.desc,id:p.id})),...projects.map(p=>({title:p.title,type:'Project',desc:p.desc,id:p.id})),...resources.map(r=>({title:r[0],type:'Resource',desc:r[1],id:'resource'}))].filter(x=>(x.title+x.desc).toLowerCase().includes(q.toLowerCase())),[q]);return <><Nav/><main className="listing"><PageHero kicker="SEARCH" title="Find your next lesson." sub="Search across paths, projects and resources."/><div className="searchbox big"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Try “Git”, “React”, “HTML”..."/></div><div className="search-results">{q&&results.map((r,i)=><button key={i} onClick={()=>go(r.type==='Learning Path'?'path':r.type==='Project'?'project':'resources',r.id)}><span>{r.type}</span><b>{r.title}</b><p>{r.desc}</p><ChevronRight/></button>)}</div></main></>}

function Auth({signup=false}:{signup?:boolean}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();localStorage.setItem('cv-user',JSON.stringify({email}));go('dashboard')};return <main className="auth"><div className="auth-glow"/><div className="auth-card"><button className="brand auth-brand" onClick={()=>go('home')}><span className="brand-mark">&lt;/&gt;</span><span>Coding<span>Vibes</span></span></button><span className="kicker">{signup?'CREATE YOUR ACCOUNT':'WELCOME BACK'}</span><h1>{signup?'Start building.':'Continue learning.'}</h1><p>{signup?'Create a free learning profile and keep your progress.':'Log in to continue your learning journey.'}</p><form onSubmit={submit}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="primary full">{signup?'Create account':'Log in'} <ArrowRight/></button></form><button className="auth-switch" onClick={()=>go(signup?'login':'signup')}>{signup?'Already have an account? Log in':'New to Coding Vibes? Create an account'}</button></div></main>}

function Dashboard(){const user=JSON.parse(localStorage.getItem('cv-user')||'null');const progress=Number(localStorage.getItem('cv-progress-html')||0);return <><Nav/><main className="dashboard-page"><div className="dash-head"><div><span className="kicker">STUDENT DASHBOARD</span><h1>Keep your momentum.</h1><p>{user?.email||'Your learning workspace'}</p></div><button className="secondary" onClick={()=>{localStorage.removeItem('cv-user');go('home')}}>Log out</button></div><div className="stats-grid"><div><span>HTML PROGRESS</span><b>{progress}/10</b><i style={{width:progress*10+'%'}}/></div><div><span>PROJECTS</span><b>3</b><small>Available to build</small></div><div><span>ROADMAP</span><b>{JSON.parse(localStorage.getItem('cv-roadmap')||'[]').length}/13</b><small>Milestones complete</small></div></div><section className="dashboard-section"><div className="section-head"><div><span className="kicker">CONTINUE LEARNING</span><h2>HTML path</h2></div><button className="text-link" onClick={()=>go('path','html')}>Open path <ArrowRight size={16}/></button></div><div className="continue-card"><div className="card-icon"><BookOpen/></div><div><b>How the web is structured</b><p>Lesson 01 · Start with the foundations.</p></div><button className="primary small" onClick={()=>go('lesson','html-1')}>Continue</button></div></section></main><Footer/></>}

function Studio(){const[tab,setTab]=useState('overview');const[title,setTitle]=useState('');const[files,setFiles]=useState('index.html\\nstyle.css\\napp.js');return <><div className="studio-shell"><aside className="studio-side"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">&lt;/&gt;</span><span>Coding<span>Vibes</span></span></button><div className="studio-nav">{[['overview','Dashboard',Layers3],['projects','Projects',Boxes],['create','Create Project',Code2],['lessons','Lessons',BookOpen],['roadmaps','Roadmaps',Route],['media','Media',Upload],['users','Users',Users],['settings','Settings',Settings]].map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id as string)} key={id}><Icon size={17}/>{label}</button>)}</div><button className="studio-exit" onClick={()=>go('home')}>Exit Studio</button></aside><main className="studio-main"><div className="studio-top"><div><span className="kicker">DEVELOPER STUDIO</span><h1>{tab==='create'?'Create a project':tab==='overview'?'Workspace overview':tab[0].toUpperCase()+tab.slice(1)}</h1></div><div className="secure"><ShieldCheck size={16}/> Protected workspace</div></div>{tab==='overview'&&<div className="studio-grid"><div><span>Published projects</span><b>3</b></div><div><span>Learning paths</span><b>6</b></div><div><span>Lessons</span><b>95+</b></div><div><span>Roadmaps</span><b>3</b></div></div>}{tab==='create'&&<div className="studio-form"><label>Project title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Responsive Portfolio"/></label><label>Description<textarea placeholder="What will students build?"/></label><label>Files / folder structure<textarea value={files} onChange={e=>setFiles(e.target.value)}/></label><div className="upload-box"><Upload/><b>Drop files here</b><span>or choose a folder. File detection and preview are prepared for the next backend connection.</span></div><button className="primary" onClick={()=>alert(title?'Draft saved locally.':'Add a project title first.')}>Save draft <Check/></button></div>}{tab!=='overview'&&tab!=='create'&&<div className="studio-placeholder"><Sparkles/><h2>{tab[0].toUpperCase()+tab.slice(1)} management</h2><p>This section is structured and ready for persistent database-backed content management.</p></div>}</main></div></>}

function App(){const r=useRoute();if(r.page==='home')return <Home/>;if(r.page==='paths')return <PathList/>;if(r.page==='path')return <PathDetail id={r.id}/>;if(r.page==='lesson')return <Lesson id={r.id}/>;if(r.page==='roadmaps')return <Roadmaps/>;if(r.page==='roadmap')return <Roadmap/>;if(r.page==='projects')return <Projects/>;if(r.page==='project')return <Project id={r.id}/>;if(r.page==='resources')return <Resources/>;if(r.page==='search')return <SearchPage/>;if(r.page==='login')return <Auth/>;if(r.page==='signup')return <Auth signup/>;if(r.page==='dashboard')return <Dashboard/>;if(r.page==='studio')return <Studio/>;return <Home/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);